routes/web.php
<?php

use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\LikesController;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\UsersController;
use App\Models\Category;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FrontendController::class, 'index'])->name('home');
Route::get('/blogs/{post}', [FrontendController::class, 'show'])->name('blogs.show')->middleware(['validateBlog']);
Route::get('/blogs/category/{category}', [FrontendController::class, 'category'])->name('blogs.category')->middleware(['validateCatgeory']);
Route::get('/blogs/tags/{tag}', [FrontendController::class, 'tag'])->name('blogs.tag')->middleware(['validateTag']);

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';


//Application Routes
Route::middleware(['auth'])->group(function () {
    Route::resource('categories', CategoriesController::class);
    Route::resource('tags', TagsController::class);
    Route::delete('posts/trash/{post}', [PostsController::class, 'trash'])->name('posts.trash');
    Route::get('posts/trashed', [PostsController::class, 'trashed'])->name('posts.trashed');
    Route::get('posts/draft', [PostsController::class, 'draft'])->name('posts.draft');
    Route::put('posts/restore/{post}', [PostsController::class, 'restore'])->name('posts.restore');
    Route::put('posts/status/{post}', [PostsController::class, 'status'])->name('posts.status');
    Route::resource('posts', PostsController::class);
    Route::post('/posts/{post}/like/{like}', [LikesController::class, 'likePost'])->name('posts.like');
});

Route::middleware(['auth', 'admin'])->group(function () {
    Route::get('/users', [UsersController::class, 'index'])->name('users.index');
    Route::put('/users/{user}/make-admin', [UsersController::class, 'makeAdmin'])->name('users.make-admin');
    Route::put('/users/{user}/revoke-admin', [UsersController::class, 'revokeAdmin'])->name('users.revoke-admin');
    Route::put('categories/status/{category}', [CategoriesController::class, 'status'])->name('categories.status');
    Route::put('tags/status/{tag}', [TagsController::class, 'status'])->name('tags.status');
});
//NOTE: Used raw url to delete category of category.destroy using javascript

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function posts()
    {
        return $this->belongsToMany(Post::class);
    }

    public function scopeStatus($query)
    {
        return $query->where('approved', '1');
    }
}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;


use App\Http\Requests\Tags\CreateTagRequest;
use App\Http\Requests\Tags\UpdateTagRequest;
use App\Models\Tag;


class TagsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware(['validateTagEdit'])->only('edit', 'update', 'destroy');
    }

    public function index()
    {
        $tags = Tag::latest('updated_at')->paginate(10);
        return view('tags.index', compact(['tags']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateTagRequest $request)
    {
        Tag::create(['name' => $request->name]);

        session()->flash('success', 'Tag created successfully!');

        return redirect(route('tags.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function show(Tag $tag)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        return view('tags.edit', compact(['tag']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTagRequest $request, Tag $tag)
    {
        $tag->name = $request->name;
        // $category->update(['name' => $request->name]);
        $tag->save();
        session()->flash('success', 'Tag updated successfully!');

        return redirect(route('tags.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        if ($tag->posts->count() > 0) {
            session()->flash('error', 'This Tag cannot be deleted!');
            return redirect(route('tags.index'));
        }
        $tag->delete();

        session()->flash('success', 'Tag deleted successfully!');

        return redirect(route('tags.index'));
    }

    public function status(Tag $tag)
    {
        if ($tag->approved) {
            if ($tag->posts()->count()) {
                session()->flash('error', 'Tag Status cannot be changed there are posts present!');
                return redirect(route('tags.index'));
            }
        }
        $tag->approved = !($tag->approved);
        $tag->save();
        session()->flash('success', 'Tag Status is changed successfully!');
        return redirect(route('tags.index'));
    }
}

resources/views/tags/create.blade.php
@extends('layouts.admin-panel.app')

@section('content')
    <div class="card p-3">
        <div class="card-header"><h2>Add New Tag</h2></div>
        <form action="{{  route('tags.store')  }}" method="POST">
            @csrf
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control @error('name') is-invalid @enderror"
                        name="name"
                        value="{{ old('name') }}"
                        placeholder="Enter Tag Name"
                        id="name">
                @error('name')
                <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                @enderror
            </div>

            <button type="submit" class="btn btn-outline-success mt-2">Submit</button>
        </form>
        </div>
    </div>
@endsection

resources/views/tags/edit.blade.php
@extends('layouts.admin-panel.app')

@section('content')
    <div class="card p-3">
        <div class="card-header"><h2>Update Tag</h2></div>
        <form action="{{  route('tags.update', $tag->id)  }}" method="POST">
            @csrf
            @method('PUT')
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control @error('name') is-invalid @enderror"
                        name="name"
                        value="{{ old('name', $tag->name) }}"
                        placeholder="Enter Tag Name"
                        id="name">
                @error('name')
                <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                @enderror
            </div>

            <button type="submit" class="btn btn-outline-warning mt-2">Edit Tag</button>
        </form>
        </div>
    </div>
@endsection

resources/views/tags/index.blade.php
@extends('layouts.admin-panel.app')

@section('content')
<div class="d-flex justify-content-end mb-3">
    <a href="{{route('tags.create')}}" class="btn btn-outline-primary">Add Tag</a>
</div>
<div class="card">
    <div class="card-header"><h2>Tags</h2></div>
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    @if(!(auth()->user()->isAdmin()))
                    <th>Status</th>
                    @endif
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach($tags as $tag)
                    <tr>
                        <td>{{ $tag->name }}</td>
                        @if(!(auth()->user()->isAdmin()))
                        <td>
                            <span class="btn btn-sm {{$tag->approved ? 'btn-outline-success' : 'btn-outline-danger'}}">
                                {{$tag->approved ? 'Approved' : 'Disapproved'}}
                            </span>
                        </td>
                        @endif
                        <td>
                            <a href="{{ route('tags.edit', $tag->id) }}" class="btn btn-sm btn-primary">
                                Edit
                            </a>
                            <button type="button" class="btn btn-sm btn-danger" onclick="displayModal({{ $tag->id }})" data-toggle="modal" data-target="#deleteModal">
                                Delete
                            </button>
                            @if(auth()->user()->isAdmin())
                            <div class="mt-2">
                                <form action="{{route('tags.status', $tag->id)}}" method="POST">
                                    @csrf
                                    @method('PUT')
                                    <button type="submit" class="btn btn-sm {{$tag->approved ? 'btn-outline-danger' : 'btn-outline-success'}}">
                                    @if (! $tag->approved)
                                        Approve <i class="fa fa-check"></i>
                                    @else
                                        Disapprove <i class="fa fa-times"></i>
                                    @endif
                                    </button>
                                </form>
                            </div>
                            @endif
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <!-- Delete Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="" method="POST" id="deleteTagForm">
            @csrf
            @method('DELETE')
        <div class="modal-body">
          Are you sure, you want to delete this tag?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-outline-danger">Delete Tag</button>
        </div>
        </form>
      </div>
    </div>
  </div>
<div class="mt-5">
    {{ $tags->links('vendor.pagination.bootstrap-4') }}
</div>

@endsection

@section('page-level-scripts')
<script>
    function displayModal(tagId) {
        var url = "/tags/" + tagId;
        $("#deleteTagForm").attr('action', url);
    }
</script>
@endsection