routes/web.php
<?php

use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\LikesController;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\UsersController;
use App\Models\Category;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FrontendController::class, 'index'])->name('home');
Route::get('/blogs/{post}', [FrontendController::class, 'show'])->name('blogs.show')->middleware(['validateBlog']);
Route::get('/blogs/category/{category}', [FrontendController::class, 'category'])->name('blogs.category')->middleware(['validateCatgeory']);
Route::get('/blogs/tags/{tag}', [FrontendController::class, 'tag'])->name('blogs.tag')->middleware(['validateTag']);

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';


//Application Routes
Route::middleware(['auth'])->group(function () {
    Route::resource('categories', CategoriesController::class);
    Route::resource('tags', TagsController::class);
    Route::delete('posts/trash/{post}', [PostsController::class, 'trash'])->name('posts.trash');
    Route::get('posts/trashed', [PostsController::class, 'trashed'])->name('posts.trashed');
    Route::get('posts/draft', [PostsController::class, 'draft'])->name('posts.draft');
    Route::put('posts/restore/{post}', [PostsController::class, 'restore'])->name('posts.restore');
    Route::put('posts/status/{post}', [PostsController::class, 'status'])->name('posts.status');
    Route::resource('posts', PostsController::class);
    Route::post('/posts/{post}/like/{like}', [LikesController::class, 'likePost'])->name('posts.like');
});

Route::middleware(['auth', 'admin'])->group(function () {
    Route::get('/users', [UsersController::class, 'index'])->name('users.index');
    Route::put('/users/{user}/make-admin', [UsersController::class, 'makeAdmin'])->name('users.make-admin');
    Route::put('/users/{user}/revoke-admin', [UsersController::class, 'revokeAdmin'])->name('users.revoke-admin');
    Route::put('categories/status/{category}', [CategoriesController::class, 'status'])->name('categories.status');
    Route::put('tags/status/{tag}', [TagsController::class, 'status'])->name('tags.status');
});
//NOTE: Used raw url to delete category of category.destroy using javascript

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage;

class Post extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $guarded = ['id'];
    protected $dates = ['published_at'];

    public function getImagePathAttribute()
    {
        return 'storage/' . $this->image;
    }


    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id');
    }

    public function author()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class)->withTimestamps();
    }

    public function usersLiked()
    {
        return $this->belongsToMany(User::class)->withTimestamps();
    }


    public function hasTag(int $tag_id): bool
    {
        return in_array($tag_id, $this->tags->pluck('id')->toArray());
    }

    public function deleteImage()
    {
        Storage::delete($this->image);
    }

    /**
     * Query Scopes
     */

    public function scopePublished($query)
    {
        return $query->where('published_at', '<=', now());
    }
    public function scopeUsers($query)
    {
        return $query->where('user_id', '=', auth()->user()->id);
    }
    public function scopeSearch($query)
    {
        $search = request('search');
        if ($search) {
            return $query->where('title', 'like', "%$search%");
        }
        return $query;
    }
    public function scopeStatus($query)
    {
        return $query->where('approved', '1');
    }
    public function scopeNotpublished($query)
    {
        return $query->where('published_at', '=', null)->orWhere('published_at', '>', now());
    }

    public function like($like)
    {
        $this->usersLiked()->updateExistingPivot(auth()->id(), ['like' => $like]);
        if ($like < 0) {
            $this->increment('dislikes_count');
        } else {
            $this->increment('likes_count');
        }
    }

    public function updateLike($like)
    {
        $this->usersLiked()->updateExistingPivot(auth()->id(), ['like' => $like]);
        if ($like < 0) {
            $this->increment('dislikes_count');
            $this->decrement('likes_count');
        } else {
            $this->increment('likes_count');
            $this->decrement('dislikes_count');
        }
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Post\CreatePostRequest;
use App\Http\Requests\Post\UpdatePostRequest;
use App\Models\Category;
use App\Models\Post;
use App\Models\Tag;
use App\Models\User;
use App\Notifications\PostApproved;
use Illuminate\Http\Request;

class PostsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware(['validateAuthor'])->only('edit', 'update', 'trash', 'destroy', 'restore');
        $this->middleware(['verifyCategoriesCount', 'verifyTagsCount'])->only('create', 'store');
        $this->middleware(['admin'])->only('status');
    }
    public function index()
    {
        if (auth()->user()->role === User::ADMIN) {
            $posts = Post::latest('updated_at')->published()->paginate(3);
        } else {
            $posts = Post::users()->latest('updated_at')->published()->paginate(3);
        }
        return view('posts.index', compact(['posts']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::status()->get();
        $tags = Tag::status()->get();
        return view('posts.create', compact(['categories', 'tags']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreatePostRequest $request)
    {
        $image = $request->file('image')->store('images/posts');
        $post = Post::create([
            'title' => $request->title,
            'excerpt' => $request->excerpt,
            'content' => $request->content,
            'image' => $image,
            'category_id' => $request->category_id,
            'user_id' => auth()->id(),
            'published_at' => $request->published_at
        ]);
        $post->tags()->attach($request->tags);
        if ($request->published_at >= now()) {
            session()->flash('success', 'Post created successfully placed in drafts. You will receive a mail on approval!');
            return redirect(route('posts.draft'));
        }
        session()->flash('success', 'Post created successfully. You will receive a mail on approval!');
        return redirect(route('posts.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $categories = Category::status()->get();
        $tags = Tag::status()->get();
        return view('posts.edit', compact(['post', 'categories', 'tags']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePostRequest $request, Post $post)
    {
        $data = $request->only(['title', 'excerpt', 'content', 'published_at', 'category_id']);
        if ($request->hasFile('image')) {
            $image = $request->image->store('images/posts');
            $data['image'] = $image;
            $post->deleteImage();
        }
        $data['approved'] = 0;
        $post->update($data);

        $post->tags()->sync($request->tags);
        if ($request->published_at >= now()) {
            session()->flash('success', 'Post updated successfully placed in drafts. You will receive mail on approval!');
            return redirect(route('posts.draft'));
        }
        session()->flash('success', 'Post updated successfully. You will receive mail on approval!');
        return redirect(route('posts.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::onlyTrashed()->findOrFail($id);
        $post->deleteImage();
        $post->forceDelete();
        session()->flash('success', 'Post deleted successfully!');
        return redirect(route('posts.trashed'));
    }

    public function trashed()
    {
        if (auth()->user()->role === User::ADMIN) {
            $trashed = Post::onlyTrashed()->paginate(10);
            return view('posts.trashed', ['posts' => $trashed]);
        } else {
            $trashed = Post::onlyTrashed()->users()->paginate(10);
            return view('posts.trashed', ['posts' => $trashed]);
        }
    }

    public function trash(Post $post)
    {
        $post->delete();
        session()->flash('success', 'Post trashed!');
        return redirect(route('posts.index'));
    }

    public function restore($id)
    {
        $trashedPost = Post::onlyTrashed()->findOrFail($id);
        $trashedPost->restore();
        session()->flash('success', 'Post restored successfully!');
        return redirect(route('posts.index'));
    }

    public function status(Post $post)
    {
        if (!$post->approved) {
            $post->author->notify(new PostApproved($post));
        }
        $post->update(['approved' => !($post->approved)]);
        session()->flash('success', 'Post Status is changed successfully. Mail sent successfully!');
        return redirect(route('posts.index'));
    }

    public function draft()
    {
        if (auth()->user()->role === User::ADMIN) {
            $posts = Post::oldest('published_at')->notpublished()->paginate(3);
        } else {
            $posts = Post::users()->latest('published_at')->notpublished()->paginate(3);
        }
        return view('posts.draft', compact(['posts']));
    }
}

resources/views/posts/create.blade.php
@extends('layouts.admin-panel.app')

@section('page-level-styles')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.css">
@endsection

@section('content')
    <div class="card">
        <div class="card-header"><h2>Add New Post</h2></div>
            <div class="card-body">
            <form action="{{  route('posts.store')  }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text"
                            class="form-control @error('title') is-invalid @enderror"
                            name="title"
                            value="{{ old('title') }}"
                            placeholder="Enter Post Title"
                            id="title">
                    @error('title')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="excerpt">Excerpt</label>
                    <input type="text"
                            class="form-control @error('excerpt') is-invalid @enderror"
                            name="excerpt"
                            value="{{ old('excerpt') }}"
                            placeholder="Enter Post Excerpt"
                            id="excerpt">
                    @error('excerpt')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="content">Content</label>
                    <input type="hidden" id="content" name="content" value="{{old('content')}}">
                    <trix-editor input="content"></trix-editor>
                    @error('content')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="Category">Category</label>
                    <select name="category_id" id="category_id" class="form-control select2">
                        <option></option>
                        @foreach ($categories as $category)
                            @if($category->id == old('category_id'))
                                <option value="{{$category->id}}" selected>{{$category->name}}</option>
                            @else
                                <option value="{{$category->id}}">{{$category->name}}</option>
                            @endif
                        @endforeach
                    </select>
                    @error('category_id')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="Tags">Tags</label>
                    <select name="tags[]" id="tags" class="form-control select2" multiple>
                        <option></option>
                        @foreach ($tags as $tag)
                            <option value="{{$tag->id}}"
                                {{ (old('tags') && (in_array($tag->id, old('tags'))) ? 'selected' : '')}}>{{$tag->name}}
                            </option>
                        @endforeach
                    </select>
                    @error('tags')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="published_at">Published At</label>
                    <input type="text"
                            class="form-control"
                            name="published_at"
                            value="{{ old('published_at') }}"
                            id="published_at">
                </div>

                <div class="form-group">
                    <label for="image">Image</label>
                    <input type="file"
                            class="form-control @error('image') is-invalid @enderror"
                            name="image"
                            id="image">
                    @error('image')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>
                <button type="submit" class="btn btn-outline-success mt-2">Submit</button>
            </form>
        </div>
    </div>
    </div>
@endsection

@section('page-level-scripts')
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.js"></script>
    <script>
        $('.select2').select2({
            placeholder: 'Select an option',
            allowClear: true
        });
        flatpickr("#published_at", {
            enableTime: true,
            dateFormat: "Y-m-d H:i"
        });
    </script>
@endsection

resources/views/posts/draft.blade.php
@extends('layouts.admin-panel.app')

@section('content')
<div class="card">
    <div class="card-header"><h2>Draft Posts</h2></div>
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                @if(auth()->user()->isAdmin())
                    <th>User</th>
                @endif
                    <th>Image</th>
                    <th>Title</th>
                    <th>Excerpt</th>
                    <th>Category</th>
                    <th>Publishing</th>
                    @if(!(auth()->user()->isAdmin()))
                    <th>Status</th>
                    @endif
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach($posts as $post)
                    <tr >
                    @if(auth()->user()->isAdmin())
                        <td>{{ $post->author->name }}</td>
                    @endif
                        <td><img src="{{ asset($post->image_path) }}" width="120"></td>
                        <td>{{$post->title}}</td>
                        <td>{{$post->excerpt}}</td>
                        <td>{{$post->category->name}}</td>
                        <td>{{$post->published_at? $post->published_at->diffForHumans(): 'NULL'}}</td>
                        @if(!(auth()->user()->isAdmin()))
                        <td>
                            <span class="btn btn-sm {{$post->approved ? 'btn-outline-success' : 'btn-outline-danger'}}">
                                {{$post->approved ? 'Approved' : 'Disapproved'}}
                            </span>
                        </td>
                        @endif
                        <td>
                            <a href="{{ route('posts.edit', $post->id) }}" class="btn btn-sm btn-primary">
                                Edit
                            </a>
                            <button type="button" class="btn btn-sm btn-danger" onclick="displayModal({{ $post->id }})" data-toggle="modal" data-target="#deleteModal">
                                Trash
                            </button>
                            @if(auth()->user()->isAdmin())
                            <div class="mt-2">
                                <form action="{{route('posts.status', $post->id)}}" method="POST">
                                    @csrf
                                    @method('PUT')

                                    <button type="submit" class="btn btn-sm {{$post->approved ? 'btn-outline-danger' : 'btn-outline-success'}}">
                                    @if (! $post->approved)
                                        Approve <i class="fa fa-check"></i>
                                    @else
                                        Disapprove <i class="fa fa-times"></i>
                                    @endif
                                    </button>

                                </form>
                            </div>
                            @endif
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <!-- Delete Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Trash post</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="" method="POST" id="trashPostForm">
            @csrf
            @method('DELETE')
        <div class="modal-body">
          Are you sure, you want to Trash this Post?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-outline-danger">Trash Post</button>
        </div>
        </form>
      </div>
    </div>
  </div>

<div class="mt-5">
    {{ $posts->links('vendor.pagination.bootstrap-4') }}
</div>

@endsection

@section('page-level-scripts')
<script>
    function displayModal(postId) {
        var url = "/posts/trash/" + postId;
        $("#trashPostForm").attr('action', url);
    }
</script>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.admin-panel.app')

@section('page-level-styles')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.css">
@endsection

@section('content')
    <div class="card">
        <div class="card-header"><h2>Edit Post</h2></div>
            <div class="card-body">
            <form action="{{  route('posts.update', $post->id)  }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text"
                            class="form-control @error('title') is-invalid @enderror"
                            name="title"
                            value="{{ old('title', $post->title) }}"
                            placeholder="Enter Post Title"
                            id="title">
                    @error('title')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="excerpt">Excerpt</label>
                    <input type="text"
                            class="form-control @error('excerpt') is-invalid @enderror"
                            name="excerpt"
                            value="{{ old('excerpt', $post->excerpt) }}"
                            placeholder="Enter Post Excerpt"
                            id="excerpt">
                    @error('excerpt')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="content">Content</label>
                    <input type="hidden" id="content" name="content" value="{{old('content', $post->content)}}">
                    <trix-editor input="content"></trix-editor>
                    @error('content')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="Category">Category</label>
                    <select name="category_id" id="category_id" class="form-control select2">
                        <option></option>
                        @foreach ($categories as $category)
                            @if($category->id == old('category_id', $post->category_id))
                                <option value="{{$category->id}}" selected>{{$category->name}}</option>
                            @else
                                <option value="{{$category->id}}">{{$category->name}}</option>
                            @endif
                        @endforeach
                    </select>
                    @error('category_id')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="Tags">Tags</label>
                    <select name="tags[]" id="tags" class="form-control select2" multiple>
                        <option></option>
                        @foreach ($tags as $tag)
                        @if((old('tags') && (in_array($tag->id, old('tags')))) || $post->hasTag($tag->id))
                            <option value="{{$tag->id}}" selected>
                                {{$tag->name}}
                            </option>
                        @else
                            <option value="{{$tag->id}}">
                                {{$tag->name}}
                            </option>
                        @endif
                        @endforeach
                    </select>
                    @error('tags')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="published_at">Published At</label>
                    <input type="text"
                            class="form-control"
                            name="published_at"
                            value="{{ old('published_at', $post->published_at) }}"
                            id="published_at">
                </div>

                <div class="form-group">
                    <label for="image">Image</label>
                    <input type="file"
                            class="form-control @error('image') is-invalid @enderror"
                            name="image"
                            id="image">
                    @error('image')
                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>
                <button type="submit" class="btn btn-outline-success mt-2">Submit</button>
            </form>
        </div>
    </div>
    </div>
@endsection

@section('page-level-scripts')
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.js"></script>
    <script>
        $('.select2').select2({
            placeholder: 'Select an option',
            allowClear: true
        });
        flatpickr("#published_at", {
            enableTime: true,
            dateFormat: "Y-m-d H:i"
        });
    </script>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.admin-panel.app')

@section('content')
<div class="d-flex justify-content-end mb-3">
    <a href="{{route('posts.create')}}" class="btn btn-outline-primary">Add Post</a>
</div>
<div class="card">
    <div class="card-header"><h2>Posts</h2></div>
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                @if(auth()->user()->isAdmin())
                    <th>User</th>
                @endif
                    <th>Image</th>
                    <th>Title</th>
                    <th>Excerpt</th>
                    <th>Category</th>
                    @if(!(auth()->user()->isAdmin()))
                    <th>Status</th>
                    @endif
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach($posts as $post)
                    <tr>
                    @if(auth()->user()->isAdmin())
                        <td>{{ $post->author->name }}</td>
                    @endif
                        <td><img src="{{ asset($post->image_path) }}" width="120"></td>
                        <td>{{$post->title}}</td>
                        <td>{{$post->excerpt}}</td>
                        <td>{{$post->category->name}}</td>
                        @if(!(auth()->user()->isAdmin()))
                        <td>
                            <span class="btn btn-sm {{$post->approved ? 'btn-outline-success' : 'btn-outline-danger'}}">
                                {{$post->approved ? 'Approved' : 'Disapproved'}}
                            </span>
                        </td>
                        @endif
                        <td>
                            <a href="{{ route('posts.edit', $post->id) }}" class="btn btn-sm btn-primary">
                                Edit
                            </a>
                            <button type="button" class="btn btn-sm btn-danger" onclick="displayModal({{ $post->id }})" data-toggle="modal" data-target="#deleteModal">
                                Trash
                            </button>
                            @if(auth()->user()->isAdmin())
                            <div class="mt-2">
                                <form action="{{route('posts.status', $post->id)}}" method="POST">
                                    @csrf
                                    @method('PUT')

                                    <button type="submit" class="btn btn-sm {{$post->approved ? 'btn-outline-danger' : 'btn-outline-success'}}">
                                    @if (! $post->approved)
                                        Approve <i class="fa fa-check"></i>
                                    @else
                                        Disapprove <i class="fa fa-times"></i>
                                    @endif
                                    </button>

                                </form>
                            </div>
                            @endif
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <!-- Delete Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Trash post</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="" method="POST" id="trashPostForm">
            @csrf
            @method('DELETE')
        <div class="modal-body">
          Are you sure, you want to Trash this Post?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-outline-danger">Trash Post</button>
        </div>
        </form>
      </div>
    </div>
  </div>

<div class="mt-5">
    {{ $posts->links('vendor.pagination.bootstrap-4') }}
</div>

@endsection

@section('page-level-scripts')
<script>
    function displayModal(postId) {
        var url = "/posts/trash/" + postId;
        $("#trashPostForm").attr('action', url);
    }
</script>
@endsection