routes/web.php
<?php

use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\LikesController;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\UsersController;
use App\Models\Category;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FrontendController::class, 'index'])->name('home');
Route::get('/blogs/{post}', [FrontendController::class, 'show'])->name('blogs.show')->middleware(['validateBlog']);
Route::get('/blogs/category/{category}', [FrontendController::class, 'category'])->name('blogs.category')->middleware(['validateCatgeory']);
Route::get('/blogs/tags/{tag}', [FrontendController::class, 'tag'])->name('blogs.tag')->middleware(['validateTag']);

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';


//Application Routes
Route::middleware(['auth'])->group(function () {
    Route::resource('categories', CategoriesController::class);
    Route::resource('tags', TagsController::class);
    Route::delete('posts/trash/{post}', [PostsController::class, 'trash'])->name('posts.trash');
    Route::get('posts/trashed', [PostsController::class, 'trashed'])->name('posts.trashed');
    Route::get('posts/draft', [PostsController::class, 'draft'])->name('posts.draft');
    Route::put('posts/restore/{post}', [PostsController::class, 'restore'])->name('posts.restore');
    Route::put('posts/status/{post}', [PostsController::class, 'status'])->name('posts.status');
    Route::resource('posts', PostsController::class);
    Route::post('/posts/{post}/like/{like}', [LikesController::class, 'likePost'])->name('posts.like');
});

Route::middleware(['auth', 'admin'])->group(function () {
    Route::get('/users', [UsersController::class, 'index'])->name('users.index');
    Route::put('/users/{user}/make-admin', [UsersController::class, 'makeAdmin'])->name('users.make-admin');
    Route::put('/users/{user}/revoke-admin', [UsersController::class, 'revokeAdmin'])->name('users.revoke-admin');
    Route::put('categories/status/{category}', [CategoriesController::class, 'status'])->name('categories.status');
    Route::put('tags/status/{tag}', [TagsController::class, 'status'])->name('tags.status');
});
//NOTE: Used raw url to delete category of category.destroy using javascript

resources/views/layouts/admin-panel/app.blade.php
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"  crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    @yield('page-level-styles')

    <title>Hello, world!</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="#">Blog It Admin Panel</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>


       <div class="collapse navbar-collapse" id="navbarSupportedContent">
           <ul class="navbar-nav ml-auto">
               <li class="nav-item dropdown">
                   <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                       {{ auth()->user()->name }}
                   </a>
                   <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                       <form action="{{ route('logout') }}" method="POST">
                           @csrf
                           <input type="submit" class="dropdown-item" value="Logout">
                       </form>

                   </div>
               </li>
           </ul>
       </div>
   </div>
</nav>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                  <ul class="nav flex-column">
                    <li class="nav-item">
                        <a href="{{route('dashboard')}}" class="nav-link">Dashboard</a>
                    </li>
                    @if(auth()->user()->isAdmin())
                    <li class="nav-item">
                        <a href="{{route('users.index')}}" class="nav-link">Users</a>
                    </li>
                    @endif
                    <li class="nav-item">
                        <a href="{{route('posts.index')}}" class="nav-link">Posts</a>
                    </li>
                      <li class="nav-item">
                          <a href="{{route('categories.index')}}" class="nav-link">Categories</a>
                      </li>
                      <li class="nav-item">
                        <a href="{{route('tags.index')}}" class="nav-link">Tags</a>
                    </li>
                    <hr>
                    <li class="nav-item">
                        <a href="{{route('posts.trashed')}}" class="nav-link">Trashed Posts</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('posts.draft')}}" class="nav-link">Draft Posts</a>
                    </li>
                    <hr>
                    <li class="nav-item">
                        <a href="{{route('home')}}" class="nav-link">Visit HomePage</a>
                    </li>
                  </ul>
                </div>
              </div>
        </div>
        <div class="col-md-9">
            @include('layouts.partials._message')
            @yield('content')
        </div>
    </div>
</div>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
@yield('page-level-scripts')
</body>
</html>